### ISSUE TITLE
Openwrt为旁路由模式下，无法获取当前ip段

### ISSUE THREAD

**Issue by wangzi023** [wukongdaily/tvhelper#1]
Openwrt为旁路由模式下，且关闭了DHCP，脚本无法主动读取当前IP段。提示`Device "br-lan" does not exist.`
![Snipaste_2024-02-20_08-40-15](https://github.com/wukongdaily/tvhelper/assets/49384237/391b83a2-3f1c-44d7-b8dd-27e83b526d34)

**建议增加手动输入ip功能**

**Comment by wukongdaily** [comment]
收到你的反馈，马上去修改。

**Comment by wukongdaily** [comment]
顺便问一句，你的j4125软路由是多个网口的吗，然后你目前的系统是iStoreOS呢还是其他编译的OpenWrt呢

**Comment by hdp521** [comment]
<img width="459" alt="image" src="https://github.com/wukongdaily/tvhelper/assets/2237903/de95b72e-38ff-4a2d-8905-1c87c2b77893">
同样的问题

**Comment by hdp521** [comment]
<img width="740" alt="image" src="https://github.com/wukongdaily/tvhelper/assets/2237903/26c02e2a-038f-4dba-a598-5138e740a89a">
另外还显示github无法连接

**Comment by wangzi023** [comment]
> 顺便问一句，你的j4125软路由是多个网口的吗，然后你目前的系统是iStoreOS呢还是其他编译的OpenWrt呢

ESXI虚拟机安装爱快做主路由，openWRT旁路由；主路由和旁路由网关互指。openWRT是自己编译的并非iStoreOS，版本是 R23.10.1 内核版本是 5.15.136

**Comment by wukongdaily** [comment]
奥你是虚拟机呀，虚拟机我确实没适配过呢，一直是物理机。暂时是不支持虚拟机的情况，不过我后面会研究一下的。
然后针对br-lan 获取不到的情况做了一些容错，遇到br-lan获取不到的时候，提示用户输入完整ip地址
https://github.com/wukongdaily/tvhelper/commit/a8cd43de341a64c894c6a0284218795aab704d1f
你一会试试吧。我估计还是不太行。 可能用虚拟机连不上。

**Comment by ihead** [comment]
我跟楼主的情况类似，也是旁路由，

但是我的 OpenWRT 是以 Docker 容器的形式跑的，主系统是 Armbian，也是挺尴尬的，

我试过用 exec 进容器里运行该脚本，也是跑不了 adb，会一直重复显示功能列表，

最后解决的方案直接在 Armbian 上跑 sudo apt install adb，再用连接，盒子就能弹验权窗口了，不过鉴于是跑在 Armbian 下，我估摸着软件直接下载路径应该跟 OpenWRT 那些不一样而导致推送不了，或者我在根目录下建个类似的 tmp/upload 好像理论上应该可行_(:зゝ∠)_

**Comment by wukongdaily** [comment]
当获取不到br-lan时候，程序会提示让输入完整的盒子ip地址的。
虚拟机用户或者docker 里的openwrt的用户。请后续直接使用docker版本的盒子助手。过几天发。
