### ISSUE TITLE
内核版本6.1.81的R2S无法安装脚本

### ISSUE THREAD

**Issue by jyxq404** [wukongdaily/tvhelper#10]
运行脚本是出现如下错误提示：
--2024-03-24 22:40:37--  https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.sh
Resolving raw.githubusercontent.com... 0.0.0.0
Connecting to raw.githubusercontent.com|0.0.0.0|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by 'O=OpenWrtD20A2EBFDC7B3603,CN=OpenWrt,L=None,ST=Somewhere,C=ZZ':
  Self-signed certificate encountered.
    ERROR: certificate common name 'OpenWrt' doesn't match requested host name 'raw.githubusercontent.com'.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.

**Comment by wukongdaily** [comment]
这是节点不给力造成的。换节点，或者换代理模式。
这些日志 会给新手很大误导。实际上本质还是网络造成的。
