### ISSUE TITLE
wget失败

### ISSUE THREAD

**Issue by kayenmok** [wukongdaily/tvhelper#14]
wget -O tv.sh https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.sh && chmod +x tv.sh && ./tv.sh

root@BleachWrt:~# wget -O tv.sh https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.sh && chmod +x tv.sh && ./tv.sh
--2024-04-01 22:40:18--  https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.sh
Resolving raw.githubusercontent.com... 198.18.0.52
Connecting to raw.githubusercontent.com|198.18.0.52|:443... connected.
Unable to establish SSL connection.

**Comment by wukongdaily** [comment]
这不是bug，这些系统log确实会误导新手。你的路由器要保持可以正确的代理。是路由器本身要具备下载github文件的能力。在大陆github网页能访问，但是github文件是无法访问的。需要路由器本身要科学上网环境。去看看代理模式或者换个节点在复测。仅仅是下载不到的问题。

**Comment by kayenmok** [comment]
这个openwrt上在跑openclash 用的fakeip模式 是策略要改一下或者变成全局模式试试？


wukongdaily ***@***.***>于2024年4月2日 周二10:51写道：
