### ISSUE TITLE
向TV端输入文字(限英文)按shift的字符没法传递

### ISSUE THREAD

**Issue by start2021-better** [wukongdaily/tvhelper#3]
![image](https://github.com/wukongdaily/tvhelper/assets/92646119/33d03b24-a41c-4364-a901-918beef1f06f)
如上图的：下横线  " _  "字符
测验了下基本都是标准键盘的数字键盘+shift键的字符：!@#$%&* _ +
辛苦悟空大师坐等修复~

**Comment by wukongdaily** [comment]
嗯 这其实不是bug。adb 本来就不支持特殊字符的。当时就是想过滤掉 ，防止报错。
我这边稍微修改了一下。稍微扩大范围。不过限于openwrt 系统下的adb的版本问题（和pc表现不一样）
不赘述了。目前支持简单网址。clash订阅地址 请使用选项10. 复杂网址请连接蓝牙键盘去输入。。
输入blue回车后进入配对模式。搜索周围的蓝牙键盘。
修改记录
https://github.com/wukongdaily/tvhelper/commit/747f4f0e24f6608eaa80bc086199cfb4a7706cfe
