### ISSUE TITLE
R4S 旁路由模式报错，无法连接

### ISSUE THREAD

**Issue by xxiieang** [wukongdaily/tvhelper#4]
盒子是小米盒子国际版
Error relocating /usr/bin/adb: RSA_size:
symbol not found

Error relocating /usr/bin/adb: BN
rd: symbol not found
_get_wo
Error relocating /usr/bin/adb: RSA
symbol not found
_free:
Error relocating /usr/bin/adb: EVP_ free: symbol not found
_PKEY_
Error relocating /usr/bin/adb: BN_ ee: symbol not found
LCIX
_f
Error relocating /usr/bin/adb: BN_ symbol not found
_free:
Error relocating /usr/bin/adb: BN_ symbol not found
_сору:
Error relocating /usr/bin/adb: BN_CTX
w: symbol not found
_ne
Error relocating /usr/bin/adb: PEM_read
RSAPrivateKey: symbol not found

Error relocating /usr/bin/adb: RSA
symbol not found
_new:
Error relocating /usr/bin/adb: EVP. new: symbol not found
_PKEY_
Error relocating /usr/bin/adb: BN_mod
r: symbol not found

Error relocating /usr/bin/adb: BN_set_bi
t: symbol not found

Error relocating /usr/bin/adb: PEM_write
PrivateKey: symbol not found

Error relocating /usr/bin/adb: RSA_sign:
symbol not found

Error relocating /usr/bin/adb: EVP.
_Encod
eBlock: symbol not found

Error
relocating /usr/bin/adb: BN div: s
ymbol not found

Error relocating /usr/bin/adb: EVP
setl
RSA: symbol not found

**Comment by wukongdaily** [comment]
R4S 安装不上adb吗 有点奇怪。第一项 安装adb 报错了吗。感觉像是固件的问题。adb都没正常运行呀。换iStoreOS试试。
然后你用的是哪个固件，发给我地址。我回头瞅瞅看

**Comment by xxiieang** [comment]
adb 安装没问题，连接的时候报错。固件是骷髅头最后一个 R4S 版本。另外用悟空助手也无法连接 adb。
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8313377&mobile=2

**Comment by wukongdaily** [comment]
帮我转存在谷歌网盘或者百度网盘吧。谢谢。另外建议你换成iStoreOS固件复测一下。

**Comment by xxiieang** [comment]
> 帮我转存在谷歌网盘或者百度网盘吧。谢谢。另外建议你换成iStoreOS固件复测一下。

通过百度网盘分享的文件：R4S
链接：https://pan.baidu.com/s/1XHdz2rhzi2Ne2vX5gJNnxg?pwd=BMA6 
提取码：BMA6 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by wukongdaily** [comment]
测试发现你的这个固件确实比较特殊，没有安装libopenssl，你可以先执行如下代码，之后在运行我的脚本就行了
 `opkg update`
 `opkg install libopenssl`
