### ISSUE TITLE
求问一下这个报错是什么意思？本人小白正在摸索学习

### ISSUE THREAD

**Issue by xander4214** [wukongdaily/tvhelper#5]
admin@RT-AX56U-E000:/tmp/home/root# wget -O tv.sh https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.s h && chmod +x tv.sh && ./tv.sh Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. --2024-03-01 18:05:34-- https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.sh Resolving raw.githubusercontent.com... 185.199.108.133 Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 30096 (29K) [text/plain] Saving to: 'tv.sh' tv.sh 100%[===================================================>] 29.39K --.-KB/s in 0.1s 2024-03-01 18:05:34 (288 KB/s) - 'tv.sh' saved [30096/30096] ./tv.sh: line 33: declare: not found ./tv.sh: line 34: declare: not found ./tv.sh: line 124: syntax error: bad for loop variable

**Comment by xander4214** [comment]
本人路由器是天邑ty6201m，刷的一个叫swrt的固件，不知道可不可以用这个命令行
![F0DFF134-0CAF-4528-AD53-523283EEB045](https://github.com/wukongdaily/tvhelper/assets/161846895/a9c324da-096e-4a35-910d-2e0574862c3e)
![F8709AD8-2C12-4AD8-BD43-266A6F5D07E4](https://github.com/wukongdaily/tvhelper/assets/161846895/adbfd10f-7d7f-4ea5-b6cf-5023a248c61c)

**Comment by wukongdaily** [comment]
你的系统不是openwrt系统，而是华硕或者梅林系统。因此脚本是不支持的。这属于正常现象。该脚本仅支持openwrt系统。你的系统虽然命名为swrt 但却不是openwrt系统。
