### ISSUE TITLE
提示找不到tv.sh

### ISSUE THREAD

**Issue by forseticn** [wukongdaily/tvhelper#7]
root@OpenWrt:~# ls
tv.sh
root@OpenWrt:~# tv.sh
-ash: tv.sh: not found
root@OpenWrt:~# wget -O tv.sh https://raw.githubusercontent.com/wukongdaily/tvhe
lper/master/shells/tv.sh && chmod +x tv.sh && ./tv.sh
--2024-03-06 17:11:44--  https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/tv.sh
Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30096 (29K) [text/plain]
Saving to: 'tv.sh'

tv.sh               100%[===================>]  29.39K  --.-KB/s    in 0.06s

2024-03-06 17:11:46 (517 KB/s) - 'tv.sh' saved [30096/30096]

-ash: ./tv.sh: not found

用ls看了下，有tv.sh，用cat看了下，内容也有。
但就是执行不了。

我是在openwrt里的ttyd终端操作的，用putty连接操作也同样的问题。

**Comment by wukongdaily** [comment]
你的路由器应该执行另一句 env.sh
`wget -O env.sh https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/env.sh && chmod +x env.sh && ./env.sh`

**Comment by forseticn** [comment]
> 你的路由器应该执行另一句 env.sh `wget -O env.sh https://raw.githubusercontent.com/wukongdaily/tvhelper/master/shells/env.sh && chmod +x env.sh && ./env.sh`

OK了 谢谢
