### ISSUE TITLE
用clash，网络使用一切，但系统一直提示未连接互联网

### ISSUE THREAD

**Issue by mykev** [wukongdaily/tvhelper#8]
我用谷歌的chromecast盒子的，我在盒子里安装了clash，网络使用一切正常，油管，奈飞，迪斯尼，亚马逊等等，都一切正常，但系统还不定时的提示 网络未连接到互联网，请问悟空大哥有遇到过吗？有什么办法解决

**Comment by wukongdaily** [comment]
是的，这属于正常现象。只有在联网之前 解决科学上网问题才能彻底去掉此提示。
比如有路由器 软路由～

**Comment by mykev** [comment]
谢谢悟空哥的解答！发自我的 iPhone在 2024年3月9日，15:16，wukongdaily ***@***.***> 写道：﻿
是的，这属于正常现象。只有在联网之前 解决科学上网问题才能彻底去掉此提示。
比如有路由器 软路由～
